create table books
(
    id          bigint generated by default as identity,
    author      varchar(255) not null,
    description text         not null,
    genre       varchar(255) not null,
    isbn        varchar(255) not null unique,
    title       varchar(255) not null,
    available   boolean      not null,
    user_id     bigint,
    primary key (id)
)