insert into books (author,
                   description,
                   genre,
                   isbn,
                   title,
                   available,
                   user_id)
values ('Remark',
        'From the quintessential author of wartime Germany, A Time to Love and a Time to Die echoes the harrowing insights of his masterpiece All Quiet on the Western Front. After two years at the Russian front, Ernst Graeber finally receives three weeks leave.',
        'Novel',
        '111-111-111',
        'A Time to Love and a Time to Die',
        true,
        null),
       ('London',
        'The Sea-Wolf is a 1904 psychological adventure novel by American writer Jack London. The book''s protagonist, Humphrey Van Weyden, is a literary critic who is a survivor of an ocean collision and who comes under the dominance of Wolf Larsen, the powerful and amoral sea captain who rescues him.',
        'Novel',
        '222-222-222',
        'The Sea Wolf',
        true,
        null),
       ('Wells',
        'The War of the Worlds is a science fiction novel by English author H. G. Wells. It was written between 1895 and 1897, and serialised in Pearson''s Magazine in the UK and Cosmopolitan magazine in the US in 1897. The full novel was first published in hardcover in 1898 by William Heinemann.',
        'Fantastic',
        '333-333-333',
        'The War of the Worlds',
        true,
        null),
       ('Tolkien',
        'The Lord of the Rings is an epic high fantasy novel by the English author and scholar J. R. R. Tolkien. Set in Middle-earth, the story began as a sequel to Tolkien''s 1937 children''s book The Hobbit, but eventually developed into a much larger work.',
        'Fantasy',
        '777-777-777',
        'The Lord of the Rings',
        true,
        null);
